# Generated by Django 4.2 on 2023-08-17 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('abdellah', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='link',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
