# Generated by Django 4.2 on 2023-08-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abdellah', '0002_work_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_name', models.CharField(max_length=50)),
                ('social_link', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.RemoveField(
            model_name='about',
            name='career',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='link',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='social_name',
        ),
    ]
