# Generated by Django 4.2 on 2023-08-17 13:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('abdellah', '0004_socials_email_socials_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='socials',
            name='icon_class',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
