# Generated by Django 4.2 on 2023-08-17 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abdellah', '0005_socials_icon_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_name', models.CharField(choices=[('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram')], max_length=20)),
                ('social_link', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='socials',
            name='icon_class',
        ),
        migrations.RemoveField(
            model_name='socials',
            name='social_link',
        ),
        migrations.RemoveField(
            model_name='socials',
            name='social_name',
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('socials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abdellah.socials')),
            ],
        ),
    ]
