# Generated by Django 4.2 on 2023-08-17 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('abdellah', '0006_sociallink_remove_socials_icon_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='socials',
        ),
        migrations.DeleteModel(
            name='SocialLink',
        ),
        migrations.AddField(
            model_name='socials',
            name='icon_class',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socials',
            name='social_link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socials',
            name='social_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
