# Generated by Django 4.2 on 2023-08-18 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('abdellah', '0007_remove_contact_socials_delete_sociallink_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socials',
            old_name='social_link',
            new_name='Facebook',
        ),
        migrations.RemoveField(
            model_name='socials',
            name='icon_class',
        ),
        migrations.RemoveField(
            model_name='socials',
            name='social_name',
        ),
        migrations.AddField(
            model_name='socials',
            name='Instagram',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socials',
            name='LinkedIn',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
