# Generated by Django 4.2 on 2023-08-18 16:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('abdellah', '0010_socials_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='picture',
            new_name='backgroudPC',
        ),
        migrations.AddField(
            model_name='home',
            name='backgroudPhone',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='picture/'),
            preserve_default=False,
        ),
    ]
