# Generated by Django 4.2 on 2023-08-18 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abdellah', '0011_rename_picture_home_backgroudpc_home_backgroudphone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='backgroudPC',
            new_name='picture',
        ),
        migrations.RemoveField(
            model_name='home',
            name='backgroudPhone',
        ),
    ]
