# Generated by Django 4.2 on 2023-08-18 16:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('abdellah', '0012_rename_backgroudpc_home_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='picturephone',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='picture/'),
            preserve_default=False,
        ),
    ]
